#Below are a few lists containing songs that categorize each genre for my generator.

pop = ["Therefore I Am by Billie Eilish", "Stupid Love by Lady Gaga", "Momentary Bliss by Gorillaz", "After Hours by The Weeknd", "foreover by Charli XCX", "Rain On Me by Lady Gaga & Ariana Grande", "Physical by Dua Lipa", "At The Door by The Strokes", "Lucid by Rina Sawayama", "Midnight Sky by Miley Cyrus", "Dynamite by BTS", "Say So by Doja Cat", "Daises by Katy Perry", "Daylight by Joji & Diplo", "Prisoner by Miley Cyrus ft. Dua Lipa", "Break My Heart by Dua Lipa", "Spotlight by Jessie Ware", "Smile by Katy Perry", "Let's Be Friends by Carly Rae Jepsen", "Levitating by Dua Lipa", "Wonder by Shawn Mendes", "Love Me Land by Zara Larsson", "You should be sad by Halsey", "Take Yourself Home by Troye Sivan", "All The Things She Said by Poppy", "Get your Wish by Porter Robinson", "People, I've been sad by Christine and the Queens", "Gentleman by Dorian Electra", "Rare by Selena Gomez", "Caution by The Killers", "Give Great Thanks by Dorian Electra", "I Love Me by Demi Lovato", "Time Flies by Tori Kelly", "I'm Ready by Sam Smith & Demi Lovato", "Nobody's Love by Maroon 5", "911 by Lady Gaga", "Love In My Pocket by Rich Brian", "Monster by Shawn Mendes & Justin Bieber" "Only the Young by Taylor Swift", "The Man by Taylor Swift", "Fever by Dua Lipa & Angèle", "Say Something by Kylie Minogue", "Ooh La La by Jessie Ware", "Bang! by AJR", "My Oh My by Camila Cabello", "Save A Kiss by Jessie Ware", "Easy by Troye Sivan", "Kings & Queens by Ava Max", "In Your Eyes by The Weeknd", "Lifetime by Romy", "Exist For Love by AURORA", "Bloody Valentine by Machine Gun Kelly", "Bikini Porn by Tove Lo", "Feel Me by Selena Gomez", "Malibu by Kim Petras", "The Other Side by SZA & Justin Timberlake", "What A Man Gotta Do by Jonas Brothers", "Wild Nothing by Foyer", "React by The Pussycat Dolls", "Birthday by Anne-Marie", "Who's Laughing Now by Ava Max", "Savage Love (Laxed- Siren Beat)[BTS Remix] by Jawsh 685, Jason Derulo, & BTS", "Feelings by Lauv", "Diamonds by Sam Smith", "Mad at Disney by salem ilese", "Lose You to Love Me by Selena Gomez", "Heather by Conan Gray", "positions by Ariana Grande", "Watermelon Sugar by Harry Styles", "Blueberry Eyes by MAX ft. SUGA", "Experience by Victoria Monét & Khalid", "Before You Go by Lewis Capaldi", "Fly Away by Tones and I", "My Oasis by Sam Smith ft. Burna Boy", "you broke me first by Tate McRae", "Know Your Worth by Khalid & Disclosure", "just a boy by Alaina Castillo", "Don't Take Me Home by Tori Kelly"]

kpop = ["Black Swan by BTS", "Ice Cream by BLACKPINK & Selena Gomez", "Stay Tonight by CHUNG HA", "pporappippam by Sunmi", "Naughty by Red Velvet- IRENE & SEULGI", "Eight by IU ft. SUGA from BTS", "Yesterday by YUKIKA", "THE BADDEST by K/DA", "DUMDi DUMDi by (G)I-DLE", "Helicopter by CLC", "What You Waiting For by SOMI", "DESSERT by HYO", "The First Step: Chapter One by TREASURE", "When We Disco by J.Y. Park & Sunmi", "Happy by TAEYEON", "2 KIDS by Taemin", "100 by SuperM", "WANNA BE MYSELF by MAMAMOO", "Who Dis? By SECRET NUMBER", "THANXX by ATEEZ", "Unknown Art Pop 2.1 by OnlyOneOf", "God's Menu by Stray Kids", "Yaya (Me Time) by Yubin", "LAST PIECE by GOT7", "Tiger Inside by SuperM", "Kick It by NCT 127", "HOME;RUN by SEVENTEEN" "J.us.T by Eyedi", "ASSA by Cignature", "I'M THE TREND by (G)I-DLE", "Nun Nu Nan Na by Cignature", "Do or Die by AleXa", "LOVELY by Minzy", "Bird by Kim Nam Joo", "La Luna by HA:TFELT", "Snowman by Brown Eyes Girls", "Paradise by SIYEON", "Take Me Now by LUNA", "It Hurts and Hurts by LUNA", "Spring by MCND", "Children by BVNDIT", "Hug Me Silently by Hyolyn & Crucial Star", "Let's Love (with Spoonz) by NU'EST", "A.I. Trooper by AleXa", "Can't You See Me? by TXT", "Still Standing by YESUNG & SURAN", "Everyone by ONF", "Road to Kingdom by ONEUS, TOO, & ONF", "In the Summer by SSAK3", "Beach Again by SSAK3", "Dreaming by KYUHYUN", "Mmmh by KAI", "Turn Back Time by WayV", "LA DI DA by EVERGLOW", "I CAN'T STOP ME by TWICE", "DUN DUN by EVERGLOW", "DAECHWITA by Agust D", "ON BY BTS", "CANDY by BAEKHYUN", "How You Like That by BLACKPINK", "Dumhdurum by Apink", "Maria by Hwasa", "Puma by TXT", "Back Door by Stray Kids", "Oh my god by (G)I-DLE", "Lovesick Girls by BLACKPINK", "Life Goes On by BTS", "You by Dynamicduo & CHEN", "Happy Day by H&D", "Lover by Kwon Jin Ah", "Unfamiliar by H&D", "Flower by Park Ji Yoon", "Something's Wrong by Kwon Jin Ah", "Refresh by ZICO & KANG DANIEL", "No Good Girl by Minseo", "Very Good by Pentagon", "Shine + Spring Snow by Pentagon", "Spit it out by Solar", "FIESTA by IZ*ONE", "WANNABE by ITZY", "Secret Story of the Swan by IZ*ONE", "INCEPTION by ATEEZ", "NOT SHY by ITZY", "NOT BY THE MOON by GOT7", "Blue Hour by TXT", "OPEN MIND by WONHO", "Boom by LAY", "Make A Wish (Birthday Song) by NCT U", "Love Killa by MONSTA X"]

rhythm_and_blues = ["Distance by Yebba", "Waiting For by rum.gold ft. Jamila Woods", "For Us by dvsn", "Heart-Shaped Box by Amber Mark", "Veg Out (Wasting Thyme) by Masego", "Plastic Plants by Mahalia", "SBCNCSLY by Black Cofee & Sabrina Claudio", "Clutch by Col3trane ft. Kiana Ledé", "My House by Elah Hale", "Forgive Me by Chloe x Halle", "Quarantine Queen by Sinead Harnett", "These Days by Tems", "DYING 4 YOUR LOVE by Snoh Aalegra", "Mad At Me. by Kiana Ledé", "It's a Moot Point by Melanie Faye", "Bittersweet by Lianne La Havas", "Good & Plenty by Alex Isley & Masego & Jack Dine", "Make Me Feel by Skip Marley ft. Ari Lennox", "Summer 2020 by Jhené Aiko", "Brandy by Full Crate ft. Kyle Dion", "So Done by Alicia Keys ft. Khalid", "Jaguar by Victoria Monét", "Only One by Gallant", "Make the Most by Lonr. ft. H.E.R.", "Bedtime Story by RINI", "Stickin' by Sinead Harnett ft. Masego & VanJess", "By Any Means by Jorja Smith", "Woman by Nao ft. Lianne La Havas", "So Much More by Xavier Omär", "More Than Enough by Alina Baraz", "Beautiful Lies (Cold) by Lol Zouaï", "Icy by Pink Sweat$", "Come Over by Jorja Smith ft. Popcaan", "Silver Tongue Devil by Masego & Shenseea", "Not Another Love Song by Ella Mai", "RUN by KWAYE", "damage by H.E.R.", "Temptation by Tiwa Savage ft. Sam Smith", "Cayendo by Frank Ocean", "Hit Different by SZA", "Black Parade by Beyoncé", "Rooted by Ciara ft. Ester Dean", "Pick Up Your Feelings by Jazmine Sullivan", "Mystery Lady by Masego & Don Toliver", "Pretend by Queen Naija", "Perfect Time by Luh Kel", "High & Dry by VanJess", "No Tomorrow, Pt.2 by Brandy ft. Ty Dolla $ign", "Always Foreover by Bryson Tiller", "Bad Habits by Usher", "safety net by Ariana Grande ft. Ty Dolla $ign", "Stuck On You by Giveon", "Crowns and Diamonds by Mario", "Do You Well By Omarion", "See What You've Done by Mary J. Blige", "I Wish by DaniLeigh ft. Ty Dolla $ign", "On and On by THEY.", "Devotion by Tone Stith", "Do It by Chloe x Halle", "Superpower by KIRBY & D Smoke", "Lovesick by RAY BLK", "By Yourself by Ty Dolla $ign ft. Mustard & Jhené Aiko", "You Ain't Worth It by Melii & 6LACK", "Pick A Side by Raiche", "Ooh Laa by John Legend", "You Save Me by Alicia Keys ft. Snoh Aalegra", "Borderline by Brandy", "Love Song by Vivian Green", "Chocolate Pomegranate by Ari Lennox", "Do It by Toni Braxton", "Sweeter by Leon Bridges ft. Terrace Martin", "Wake Up Love by Teyana Taylor ft. IMAN", "Counterfeit by IMAN"]

hip_hop = ["Wash Us in the Blood by Kanye West", "WAP by Cardi B & Megan Thee Stallion", "@ MEH by Playboi Carti", "Toosie Slide by Drake", "Bald! by JPEGMAFIA", "GOOBA by 6ix9ine", "THE SCOTTS by Travis Scott & Kid Cudi", "The Adventures of Moon Man and Slim Shady by Eminem & Kid Cudi", "Franchise by Travis Scott", "iPhone by Rico Nasty", "Pig Feet by Terrace Martin & Denzel Curry", "Laugh Now Cry Later by Drake", "Sasuke by Lil Uzi Vert", "Leader of the Delinquents by Kid Cudi", "Holiday by Lil Nas X", "Life Is Good by Future", "The Plan by Travis Scott", "Covered in Money! by JPEGMAFIA", "Ego Death by Ty Dolla $ign", "That Way by Lil Uzi Vert", "N.S.T. by BROCKHAMPTON", "Ooh LA LA by Run The Jewels", "Lewis Street by J. Cole", "Say the Name by clipping.", "Lockdown by Anderson.Paak", "Righteous by Juice WRLD", "The Bigger Pciture by Lil Baby", "Snow On Tha Bluff by J. Cole", "Fall Slowly by Joyner Lucas ft. Ashanti", "Whole World by Earl Sweatshirt", "Darkness by Eminem", "SUGAR (Remix) by BROCKHAMPTON", "Nah Nah Nah (Remix) by Kanye West", "Don't Stop by Megan Thee Stallion", "Chicago Freestyle by Drake", "Sum Bout U by 645AR", "Smile by Juice WRLD & The Weeknd", "Savage Remix by Megan Thee Stallion", "Song 33 by Noname", "Yikes by Nicki Minaj", "death bed by Powfu", "Popstar by DJ Khaled ft. Drake", "4 Da Trap by 645AR", "Godzilla by Eminem", "Boss Bitch by Doja Cat", "Turks by Nav & Gunna", "Greece by DJ Khaled", "Will by Joyner Lucas", "Burn The Hoods by Ski Mask The Slump God", "Over Your Head by Future & Lil Uzi Vert", "OHFR? by Rico Nasty", "Rodeo (Remix) by Lil Nas X", "Oprah's Bank Account by Lil Yachty & DaBaby", "When To Say When by Drake", "nhs by slowthai", "Violence by Yung Lean", "ENEMY by slowthai", "Gifted by Cordae", "keep your distance by Ameer Vann", "Compensating by Aminé", "Entrepeneur by Pharell Williams ft. Jay-Z", "Patek by Future & Lil Uzi Vert", "hooligan / sons & critics by Baby Keem", "Blueberry Faygo by Lil Mosey", "Shimmy by Aminé", "All Week by Rod Wave", "Finally Rich by Lil Eazzyy", "Cancelled by Larray", "Lets Link by WhoHeem ft. Tyga & Lil Mosey", "MAD by 2KBABY", "Revenge by $NOT", "The Parables by Cordae", "Loser by Rico Nasty ft. Trippie Redd", "For The Night by Pop Smoke ft. Lil Baby & DaBaby", "Gucci Peacoat by DaBaby", "Wolves by Big Sean ft. Post Malone", "Gorgeous by SAINt JHN", "I Got You by Trippie Redd", "Runnin by 21 Savage & Metro Boomin"]

rock = ["Kyoto by Phoebe Bridgers", "If You're Too Shy (Let Me Know) by The 1975", "Hollywood by Car Seat Headrest", "Describe by Perfume Genius", "There Must Be More Than Blood by Car Seat Headrest", "Martin by Car Seat Headrest", "sweater by black midi", "Swim / Closure by Avenade", "Leave It Alone by Hayley Williams", "Ohms by Deftones", "Caution by The Killers", "Oh Yeah! by Green Day", "(Don't Let The Dragon) Draag On by King Krule", "Mister Whisper / J Frusciante by Avenade", "Alone, Omen 3 by King Krule", "Bloody Valentine by Machine Gun Kelly", "Catatonia by Orchid Inc.", "Roses/Lotus/Violet/Iris by Hayley Williams", "Honey by King Gizzard and the Lizard Wizzard", "Nature in Three Movements by Alexis Marshall", "Science Fair by Black Country, New Road", "Is Everybody Going Crazy? by Nothing But Thieves", "Favorite Flavor by Vetromn", "FULL OF HEALTH by HEALTH", "Black Lungs by Architects", "Sleeping with the Enemy by Butcher Babies", "Demon Fire by AC/DC", "Down by Love adn Death", "Dear Anxiety by Matthew K. Heafy, Dines X Heafy, & Jared Dines", "Fight by Hyro The Hero ft. HELLYEAH & Chad Gray of Hellyeah", "25 by The Pretty Reckless", "Coming Up Roses by Starbenders", "Rise As Equals by Saul", "Yeah Right by Evanescence", "Age of Machine by Greta Van Fleet", "Our Love Will Change The World by ALice Cooper", "Shot In The Dark by AC/DC", "Somebody That I Used to Know by Three Days Grace", "Obey by Bring Me The Horizon", "Error by Deftones", "DOA by I Prevail ft. Joyner Lucas", "DON'T CHASE THE DEAD by Marilyn Manson", "Idol by Hollywood Undead ft. Tech N9ne", "Broken World by Five Finger Death Punch", "30 by Badflower", "Death By Rock And Roll by The Pretty Reckless", "My Way, Soon by Greta Van Fleet", "Limits by Bad Omens", "Beg by Seether", "Animals by Architects", "King of Misery by Saul", "Use My Voice by Evanescence", "B12 by Grey Daze", "Again by Black Stone Cherry", "Bruised And Bloodied by Seether", "Wrong Side of Heaven (Acoustic) by Five Finger Death Punch", "The Heresy by Mushroomhead", "Save Us by Atreyu", "Black Eyes Blue by Corey Taylor", "Bottom of a Bottle by Butcher Babies", "Wasteland by Seether", "Deliverance by Ego Kill Talent", "Take Me Away by Ayron Jones", "Breathe Again by Pop Evil", "Dead Man Walking by Skillet", "The Kingdom by Bush", "A Secret Door by Avatar", "Blood From A Stone by Sevendust", "Inner Calm from Outer Storms by Killer Be Killed", "Hands Up by Dead Sara", "Distance by Clint Lowery"]

latin = ["Verte by Nicki Nicole, Dread Mar I, & Bizarrap", "Lento (Remix) by Lauren Jauregui & Rauw Alejandro", "Confiesalo by Maria Beccera & Rusherking", "Navidad Solita by La Ross Maria", "CHIMBITA by Feid & Sky Rompiendo", "Tus Besos (Remix) by Juanka & Jay Wheeler", "Otra Vez by Diablo & KHEA", "Wu Wu by Sen Senra & Feid", "te pongo mal(prendelo) by Kali Uchis", "OUCH by Mau y Ricky", "La Diferente by Pitizion", "Por Fin by Corina Smith", "Cara Bonita by Nacho", "Noches de Soledad by Dylan Fuentes", "De Vuelta Pa' La Vuelta by Daddy Yankee & Marc Anthony", "DÁKITI by Bad Bunny", "BICHOTA by KAROL G", "Vida de Rico by Camilo", "LA NOCHE DE ANOCHE by Bad Bunny & ROSALÍA", "Hawái (Remix) by Maluma & The Weeknd", "De Cora <3 by Rauw Alejandro", "Polvo by Nicky Jam & Mykle Towers", "Jeans by Justin Quiles", "La Luz by Sech & J Balvin", "La Nota by Manuel Turizo, Myke Towers, & Rauw Alejandro", "No Drama by Becky G & Ozuna", "Billetes by Play-N-Skillz, Nicky Jam, & Natanael Cano", "Reloj by Rauw Alejandro", "Mi Cuarto by Jerry Di", "Don Don by Daddy Yankee, Anuel AA, & Kendo Kaponi", "Amantes y Amigos by Arcangel", "Me Gusta by Anitta ft. Cardi B & Myke Towers", "Caramelo by Ozuna, KAROL G, & Nyke Towers", "Contigo by Nacho & Greeicy", "Ponte Pa' Mi by Justin Quiles", "Del Mar by Ozuna & Sia", "Diosa (Remix) by Myke Towers, Anuel AA, & Natti Natasha", "Nada by Cali Y El Dandee & Danna Paola", "Mi Regalo Mas Bonito by La Ross Maria", "Despeinada by Ozuna & Camilo", "UN DIA (ONE DAY) by J Balvin, Dua Lipa, Bad Bunny, & Tainy", "La Curiosidad by Jay Wheeler & DJ Nelson", "Dembow 2020 by Yandel", "Anaranjado by Jowell & Randy", "Relaciones by Lunay", "Gistro Amarillo by Ozuna & Wisin", "Kobe En LA by Jhay Cortez", "Ponme al Dia by Yandel", "Enemigos Ocultos by Ozuna, Wisin, & Myke Towers ft. Arcangel, Juanka, & Cosculluela", "Elegí (Remix) by Rauw Alejandro ft. Farruko, Anuel AA, Sech, & Dímelo Flow", "Lento by Mr Eazi", "Baby by Sfera Ebbasta", "Tusa by KAROL G & Nicki Minaj", "TKN by ROSALÍA & Travis Scott", "Singapur by El Alfa", "Medusa by Jhay Cortez, Anuel AA, & J Balvin", "Tak Tiki Tak by Harry Nach", "Enjoy Yourself by Pop Smoke ft. KAROL G", "Narcos by Anuel AA", "Baila by Karl Wine ft. Tampa Curhat & Tribal Kush", "Trap Pea by El Alfa & Tyga", "Tocame by Sak Noel, Salvi, & Franklin Dam", "fue mejor by Kali Uchis", "Que Calor by Major Lazer ft. J Balvin & El Alfa", "Uchi Wala by Maffio"]

dancehall = ["Miss You Most (At Christmas) by Naomi Cowan", "So Brutal by Chronixx", "Tropics by Tessellated", "Doh Wah Love by Nessa Preppy", "Big Deal by Nailah Blackman", "Oh Lawd by Stylo G", "Smooth by Jahvillani ft. Skillibeng", "True Colors by TeeJay", "Bad Alone by Shenseea", "Close To You by Collie Buddz", "High Life by Machel Montano", "Tender by Patrice Roberts", "Quarantine Slide by Runkus", "Restless by Lu City", "Thief Piece by Problem Child", "Gwan Fi Money by David Lyn ft. Tarrus Riley", "Superhero by Hey Choppi", "Seen It Before by Busy Signal", "Platinum by Briani ft. Christopher Martin", "Keep Moving by David Lyn", "Call Me If by Dexta Daps", "Scarface by El ALfa, Play-N-Skillz, & Farruko", "Call To Duty by Beres Hammond", "Shine by Freetown Collective", "Can't Let You Go by Stefflon Don", "Tiny by Major Lazer ft. BEAM & Shenseea", "Pressure (Remix) by Koffee ft. Buju Banton", "Fresh & Clean by Jaz Elise ft. Govana", "Lighter by Tarrus Riley ft. Shenseea & Rvssian", "Too Many Feelings by Jimmy October", "Pity by Navy", "SUH ME LUV IT by Popcaan ft. Jada Kingdom", "Through the Window by Kranium", "Bumpa by Lisa Mercedez", "PSYCHO by BEAM", "Dream Girl (Global Remix) by Ir Sais, Sean Paul, & Davido", "No Selfie by Lutan Fyah", "Fast Fast (Raw) by Landmark Records ft. DEMARCO", "Jus Zess by Noise Cans & Drew Thoven ft. cKush & Sir Jay Anderson", "Start Up by Patrice Roberts & Kemar Highcon", "Outside by Rheon Elbourne & Jahllano", "Say Less by Medz Boss & Nailah Blackman", "Dancing Away by Voice", "Dumpling (Remix) by Stylo G ft. Sean Paul & Spice", "The Sidechick Song by Shenseea", "Any Weather by Vybz Kartel", "Bum Pon It by HoodCelebrityy", "Scotch & Soda by Squash", "Numbers Don't Lie by Popcaan", "Sure Sure by Shenseea", "Nah Mad (Ova Nuh Gyal) by Munga Honorable", "Moon Walk by Vybz Kartel & Squash", "Yuh Betta (50 Bag Freestyle) by Jada Kingdom", "Brik Pan Brik by Skillibeng", "Fix Tings by Demarco", "In Stock (Raw) by Vybz Kartel", "Different Rankin by Squash", "Budum by Jada Kingdom", "Oh Ye by Aidonia", "Run Di Road by HoodCelebrityy", "100% by Busy Signal ft. Afro B", "Deh Yah by Gyptian ft. Colli Buddz & Ricky Blaze", "Aircraft by Aidonia", "Elite Only by Alkaline", "Limited Edition by Shenseea", "Pretty Pon Snap by Daddy1", "Rich by Masicka", "So Me Move by Kranium"]


def create_genre(songs):
    genre = ""
    song_number = random.randint(0, len_(songs) - 1)
    for item in range(15):
        song_to_pop = random.randint(0, len(songs) - 1)
        genre += songs.pop(song_to_pop) + " "
#The for loop shown above is using the pop method to keep the list from iterating duplicates of songs so that the generator would not continuously show the same songs repeatedly. Hopefully, each song will be seen at least once.
    return genre
#In the repl.it terminal, it states that "random" is undefined and I am not sure how and what to define it as so that my program could run successfully.

print ("Choose a genre: Pop, K-Pop, R&B, Hip-Hop, Rock, Latin, or Dancehall.")
genre = input()

#Below are a series of if else statements I created for user input so that they could pick a genre to create a random playlist.
if (genre == "Pop"):
    print create_genre(pop)
    print (pop, sep = "\n")
if (genre == "K-Pop"):
    print create_genre(kpop)
    print (kpop, sep = "\n")
if (genre == "R&B"):
    print create_genre(rhythm_and_blues)
    print (rhythm_and_blues, sep = "\n")
if (genre == "Hip-Hop"):
    print create_genre(hip_hop)
    print (hip_hop, sep = "\n")
if (genre == "Rock"):
    print create_genre(rock)
    print (rock, sep = "\n")
if (genre == "Latin"):
    print create_genre(latin)
    print (latin, sep = "\n")
if (genre == "Dancehall"):
    print create_genre(dancehall)
    print (dancehall, sep = "\n")
else:
    print ("Please pick a genre. I worked hard on this.")
